# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(643, 180)
        self.path = QtWidgets.QLineEdit(Dialog)
        self.path.setGeometry(QtCore.QRect(240, 40, 361, 41))
        self.path.setObjectName("path")
        self.output = QtWidgets.QLineEdit(Dialog)
        self.output.setGeometry(QtCore.QRect(240, 90, 361, 41))
        self.output.setObjectName("output")
        self.browse = QtWidgets.QPushButton(Dialog)
        self.browse.setGeometry(QtCore.QRect(20, 40, 211, 41))
        self.browse.setObjectName("browse")
        self.run = QtWidgets.QPushButton(Dialog)
        self.run.setGeometry(QtCore.QRect(20, 90, 211, 41))
        self.run.setObjectName("run")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.browse.setText(_translate("Dialog", "Browse"))
        self.run.setText(_translate("Dialog", "RUN"))
        self.label.setText(_translate("Dialog", "Target File"))
